### ISSUE TITLE
With this package its possible to create Table that don't refresh the page upon create?

### ISSUE THREAD

**Issue by samuk190** [Okipa/laravel-table#29]
I didnt find anything about it

**Comment by Okipa** [comment]
Hi @samuk190, could you be more explicit about what you are trying to achieve (use case)? I may be able to point you in the right direction.

**Comment by samuk190** [comment]
> Hi @samuk190, could you be more explicit about what you are trying to achieve (use case)? I may be able to point you in the right direction.

I have a form to create a product, but each product have his own subproducts, I want to be able to add,edit, and update these subproducts when creating a new product.
I tried with ajax(DataTables) but didnt manage to work with backpack admin, as it loads the datatables twice.

**Comment by Okipa** [comment]
Well, it seems to be an architecture question rather than this package use.

However, here is the way I would simply build this kind of architecture :
1. I would manage the product creation without any sub-product management as my product doesn't really exist yet.
2. I would redirect toward the product edition page after the product creation, displaying a new `laravel-table` with the sub-products, allowing to manage all the sub-products (creating, editing, deleting) on the related product.

As soon as you want to allow the creation of sub-products for a product that is not already created, you expose yourself to build more complicated architecture and it is sometimes not really worth it.
