### ISSUE TITLE
Problem referencing Foreign key in table

### ISSUE THREAD

**Issue by pork94** [Okipa/laravel-table#65]
I am having issue referencing a foreign key to the name.

The model structure is as follows:
- Class has many teachers
- Teachers belong to class

I am now creating the teacher table to show the information associated with it including the class name. However i am only able to display the class ID(foreign key) instead of the class name.

I saw the custom value option and tried the following code to reference the name from the foreign ID via laravel eloquent relationship but to no avail.

```
$table->column('class')->value(function(Teacher $teacher) {
            return config('teacher.class' . $teacher->class->name);
});

```
Would appreciate any help!

**Comment by Okipa** [comment]
Hi @pork94, I would need to see you entire table configuration (class) in order to see exactly what could be going wrong.

You're solution should be working but you will not be able to sort or search results if you call `->value()` or `->html()` as it only formats the output and the SQL request will not be aware of what should be sorted or searched.

**Comment by Okipa** [comment]
@pork94, I'm closing this as the issue seems to be quite inactive.

Please comment this issue if you still struggle to do what you intend to.
