### ISSUE TITLE
Is this package compatible with the latest versions of Laravel namely 8 and 9 ???

### ISSUE THREAD

**Issue by chegmarco1989** [Okipa/laravel-table#82]
Hello.

I would like to know if this package is compatible with the latest versions of Laravel, namely Lavarel 8 and Laravel 9 ???

Please enlighten me please.

**Comment by Okipa** [comment]
I think there is a misunderstanding here: I'm not working on a v5 for compatibility purpose but in order to improve the package and to provide additional features.

Anyway, my package are always compatible with the current and previous PHP and Laravel versions in order to keep code clean, modern and easily maintainable.

As so, the v4 of this package is compatible with PHP 7.4 and 8.0 and with Laravel 7 and 8.

It will be compatible with PHP 8.0 and 8.1 and with Laravel 8 and 9 when the v5 will be released.
